<?php
/**
 * Données du site — modifier ici pour mettre à jour le contenu
 */

// ─── EXPÉRIENCES ────────────────────────────────────────────────────────────
$experiences = [
    [
        'period'   => 'Oct. 2025 — Présent',
        'role'     => 'Directeur Général & Co-fondateur',
        'company'  => 'Odonaview',
        'logo'     => '/assets/img/logos/odonaview.png',
        'tags'     => ['IA Vision', 'Sécurité critique', 'Direction générale'],
        'desc'     => 'Reprise et transformation d\'Evitech. Pilotage stratégique et technique de la solution de vidéo-intelligence JAGUAR/LYNX pour sites critiques (nucléaire, défense, énergie).',
        'current'  => true,
    ],
    [
        'period'   => 'Juin 2021 — Présent',
        'role'     => 'Président — Directeur Général',
        'company'  => 'SYIT',
        'logo'     => '/assets/img/logos/syit.svg',
        'tags'     => ['Infrastructure', 'Réseaux', 'Sécurité', 'BGP'],
        'desc'     => 'Bureau d\'étude IT indépendant. Conception, déploiement et opération d\'infrastructures réseau, serveurs et cybersécurité pour PME et grands comptes.',
        'current'  => true,
    ],
    [
        'period'   => 'Avr. 2025 — Présent',
        'role'     => 'Expert Infrastructures Numériques',
        'company'  => 'Thotario',
        'logo'     => '',
        'tags'     => ['Conseil', 'Infrastructure'],
        'desc'     => 'Accompagnement expert en infrastructures numériques.',
        'current'  => true,
    ],
    [
        'period'   => 'Nov. 2021 — Mar. 2024',
        'role'     => 'Ingénieur Systèmes & Réseaux — Board Member',
        'company'  => 'Systailor',
        'logo'     => '',
        'tags'     => ['SD-WAN', 'Systèmes', 'Réseaux'],
        'desc'     => 'Ingénierie systèmes et réseaux, participation au conseil d\'administration.',
        'current'  => false,
    ],
    [
        'period'   => 'Oct. 2023 — Fév. 2024',
        'role'     => 'Directeur de l\'Information (DSI)',
        'company'  => '100BON',
        'logo'     => '',
        'tags'     => ['DSI', 'ERP', 'Stratégie digitale'],
        'desc'     => 'Direction du système d\'information, stratégie digitale, refonte ERP et marketplace cosmétique.',
        'current'  => false,
    ],
    [
        'period'   => 'Sep. 2019 — Avr. 2022',
        'role'     => 'Responsable R&D / Chef de projet',
        'company'  => 'iCOW Systems',
        'logo'     => '',
        'tags'     => ['R&D', 'Produit', '4G/5G industriel'],
        'desc'     => 'Création d\'un routeur 4G/5G industriel, management d\'équipes franco-chinoises, développement produit IoT.',
        'current'  => false,
    ],
    [
        'period'   => 'Nov. 2018 — Juin 2021',
        'role'     => 'Consultant / Gérant',
        'company'  => 'Guillaume Robier (EI)',
        'logo'     => '',
        'tags'     => ['Conseil', 'Freelance', 'Infrastructure'],
        'desc'     => 'Missions de conseil en infrastructure, réseaux et sécurité auprès de PME.',
        'current'  => false,
    ],
    [
        'period'   => 'Oct. 2018 — Sep. 2019',
        'role'     => 'Alternant — Ingénieur Réseaux & Virtualisation',
        'company'  => 'iCOW Systems',
        'logo'     => '',
        'tags'     => ['Alternance', 'Virtualisation', 'Réseaux'],
        'desc'     => 'Ingénierie réseaux et virtualisation en alternance.',
        'current'  => false,
    ],
    [
        'period'   => 'Juin — Sep. 2018',
        'role'     => 'Stagiaire Ingénieur Réseaux',
        'company'  => 'GreenYellow (Île Maurice)',
        'logo'     => '/assets/img/clients/greenyellow.png',
        'tags'     => ['Stage', 'SCADA', 'Réseaux industriels'],
        'desc'     => 'Sécurité SCADA, 64 automates, réseau longue distance Ubiquiti sur sites énergie.',
        'current'  => false,
    ],
    [
        'period'   => 'Juil. 2017',
        'role'     => 'Stagiaire Technicien Réseaux',
        'company'  => 'Axians C&S Lyon',
        'logo'     => '',
        'tags'     => ['Stage', 'Réseaux'],
        'desc'     => 'Stage technicien réseaux.',
        'current'  => false,
    ],
    [
        'period'   => 'Juil. — Août 2016',
        'role'     => 'Technicien Réseaux',
        'company'  => 'SYS E.N.R.',
        'logo'     => '',
        'tags'     => ['Réseaux'],
        'desc'     => 'Mission technicien réseaux.',
        'current'  => false,
    ],
];

// ─── FORMATION ──────────────────────────────────────────────────────────────
$formations = [
    [
        'period'  => '2016 — 2020',
        'diploma' => 'Diplôme d\'Ingénieur Informatique & Réseaux',
        'school'  => 'CPE Lyon',
        'logo'    => '/assets/img/logos/cpe_lyon.png',
        'desc'    => 'École d\'ingénieurs en informatique, réseaux et systèmes embarqués.',
    ],
    [
        'period'  => '2018 — 2019',
        'diploma' => 'Master 2 SRIV — Systèmes Réseaux Images Virtualisation',
        'school'  => 'Université Claude Bernard Lyon 1',
        'logo'    => '/assets/img/logos/univ_lyon1.png',
        'desc'    => 'Master spécialisé en virtualisation et architectures réseaux avancées.',
    ],
    [
        'period'  => '2014 — 2016',
        'diploma' => 'Classes Préparatoires — Techniques des Sciences Industrielles',
        'school'  => 'Lazaristes Lyon',
        'logo'    => '',
        'desc'    => 'Prépa TSI.',
    ],
    [
        'period'  => '2011 — 2014',
        'diploma' => 'Baccalauréat STI2D',
        'school'  => 'Lazaristes Lyon',
        'logo'    => '',
        'desc'    => 'Sciences et Technologies de l\'Industrie et du Développement Durable.',
    ],
];

// ─── RÉALISATIONS ────────────────────────────────────────────────────────────
$realisations = [
    [
        'id'      => 'streamforge',
        'title'   => 'StreamForge — Plateforme de streaming GPU',
        'client'  => 'Client confidentiel',
        'sector'  => 'Media & Tech',
        'year'    => '2024',
        'desc'    => 'Conception et déploiement d\'une plateforme de streaming GPU haute performance. 7 Tesla P40, stockage ZFS RAIDZ1 NVMe, serveur MediaMTX, API FastAPI, interface React 18/WebRTC, base PostgreSQL + Redis.',
        'stack'   => ['GPU Cluster', 'ZFS NVMe', 'MediaMTX', 'FastAPI', 'React 18', 'WebRTC', 'PostgreSQL', 'Redis'],
        'impact'  => 'Latence sub-50ms, disponibilité 99.9%, traitement flux HD en temps réel',
        'icon'    => 'server',
    ],
    [
        'id'      => 'migration-openstack',
        'title'   => 'Migration OpenStack/Virtuozzo à chaud',
        'client'  => 'Hébergeur (confidentiel)',
        'sector'  => 'Hébergement',
        'year'    => '2023',
        'desc'    => 'Migration à chaud de 62 VMs réparties sur 3 sous-réseaux depuis OpenStack/Virtuozzo vers infrastructure Proxmox. Zéro interruption de service pour les clients finaux.',
        'stack'   => ['OpenStack', 'Virtuozzo', 'Proxmox', 'Linux', 'Python'],
        'impact'  => '62 VMs migrées, 0 downtime, économie de 40% sur les coûts de licence',
        'icon'    => 'layers',
    ],
    [
        'id'      => 'securite-seveso',
        'title'   => 'Sécurisation périmétrique sites SEVESO & nucléaires',
        'client'  => 'EDF, ORANO, Eutelsat',
        'sector'  => 'Nucléaire / Énergie / Défense',
        'year'    => '2025',
        'desc'    => 'Déploiements du système JAGUAR (Odonaview) sur sites à contraintes critiques : EDF, ORANO MELOX, Eutelsat, RTE. Détection d\'intrusion périmétrique par IA vidéo.',
        'stack'   => ['JAGUAR', 'IA Vision', 'Linux embarqué', 'ONVIF', 'VMS'],
        'impact'  => '5 sites critiques sécurisés, conformité réglementaire, taux de fausse alarme < 1%',
        'icon'    => 'shield',
    ],
    [
        'id'      => 'vxlan-evpn',
        'title'   => 'Architecture VXLAN/EVPN multi-datacenter',
        'client'  => 'SYIT — Clients internes',
        'sector'  => 'Infrastructure',
        'year'    => '2023',
        'desc'    => 'Conception et déploiement d\'une architecture réseau VXLAN/EVPN sur MikroTik avec Proxmox et BGP (AS61193). Infrastructure haute disponibilité multi-datacenter.',
        'stack'   => ['MikroTik', 'VXLAN', 'EVPN', 'BGP', 'Proxmox'],
        'impact'  => 'Segmentation L2 sur L3, failover automatique < 1s, ASN public opéré',
        'icon'    => 'network',
    ],
    [
        'id'      => 'routeur-4g-icow',
        'title'   => 'Routeur 4G/5G industriel — iCOW',
        'client'  => 'iCOW Systems',
        'sector'  => 'IoT / Industrie',
        'year'    => '2022',
        'desc'    => 'Création de A à Z d\'un routeur 4G/5G industriel IoT. Management d\'équipes franco-chinoises, développement firmware embarqué, certifications, go-to-market.',
        'stack'   => ['Linux embarqué', '4G/5G', 'IoT', 'OpenWRT', 'C/C++'],
        'impact'  => 'Produit lancé sur le marché, déployé chez plusieurs clients industriels',
        'icon'    => 'router',
    ],
    [
        'id'      => 'dsi-100bon',
        'title'   => 'DSI & Stratégie digitale — 100BON',
        'client'  => '100BON',
        'sector'  => 'E-commerce / Cosmétique',
        'year'    => '2024',
        'desc'    => 'Direction complète du SI : stratégie digitale, refonte ERP, déploiement marketplace cosmétique, automatisation des flux commerciaux.',
        'stack'   => ['Dolibarr', 'WooCommerce', 'n8n', 'AWS', 'Stripe'],
        'impact'  => 'Réduction de 60% du temps de traitement des commandes, marketplace opérationnelle',
        'icon'    => 'briefcase',
    ],
    [
        'id'      => 'greenyellow-maurice',
        'title'   => 'Sécurité SCADA — GreenYellow Île Maurice',
        'client'  => 'GreenYellow',
        'sector'  => 'Énergie renouvelable',
        'year'    => '2018',
        'desc'    => 'Sécurisation réseau SCADA sur sites énergie renouvelable. 64 automates industriels, réseau longue distance Ubiquiti, segmentation OT/IT.',
        'stack'   => ['Ubiquiti', 'SCADA', 'Modbus', 'Siemens', 'VPN'],
        'impact'  => '64 automates sécurisés, visibilité temps réel, conformité IEC 62443',
        'icon'    => 'zap',
    ],
    [
        'id'      => 'erp-automatisation',
        'title'   => 'Stack ERP & automatisation IA',
        'client'  => 'SYIT / Clients PME',
        'sector'  => 'Gestion d\'entreprise',
        'year'    => '2024',
        'desc'    => 'Déploiement Dolibarr personnalisé + n8n en intégration bidirectionnelle avec CRM et enrichissement IA. Automatisation des devis, factures et relances.',
        'stack'   => ['Dolibarr', 'n8n', 'CRM', 'LLM', 'REST API'],
        'impact'  => '-70% de saisie manuelle, enrichissement automatique des fiches prospects',
        'icon'    => 'cpu',
    ],
    [
        'id'      => 'waf-safeline',
        'title'   => 'Déploiement SafeLine WAF + Zulip self-hosted',
        'client'  => 'Client IT (confidentiel)',
        'sector'  => 'Cybersécurité',
        'year'    => '2024',
        'desc'    => 'Sécurisation applicative avec SafeLine WAF (reverse proxy) + déploiement Zulip self-hosted pour communication d\'entreprise sécurisée.',
        'stack'   => ['SafeLine', 'WAF', 'Zulip', 'Docker', 'Nginx', 'TLS'],
        'impact'  => 'Blocage de 100% des tentatives d\'injection SQL/XSS, souveraineté des données',
        'icon'    => 'lock',
    ],
    [
        'id'      => 'sdwan-systailor',
        'title'   => 'Refonte SD-WAN multi-sites',
        'client'  => 'Systailor',
        'sector'  => 'Infrastructure réseau',
        'year'    => '2023',
        'desc'    => 'Conception et déploiement d\'une architecture SD-WAN multi-sites pour mutualiser la connectivité et améliorer la résilience du réseau étendu.',
        'stack'   => ['MikroTik', 'SD-WAN', 'BGP', 'OSPF', 'VPN IPsec'],
        'impact'  => 'Résilience améliorée, bande passante mutualisée, PRA automatique',
        'icon'    => 'globe',
    ],
];

// ─── EXPERTISES ─────────────────────────────────────────────────────────────
$expertises = [
    [
        'id'    => 'securite',
        'icon'  => 'shield',
        'title' => 'Conseil en sécurité',
        'short' => 'Audit, hardening, SIEM, WAF, Zero Trust',
        'desc'  => 'Accompagnement complet en cybersécurité : audit d\'architecture, hardening systèmes, déploiement de solutions SIEM, WAF applicatif, segmentation réseau et stratégie Zero Trust. Expérience sur des sites à très haute criticité (nucléaire, défense, énergie).',
        'tech'  => ['FortiGate', 'SafeLine WAF', 'Wazuh', 'Suricata', 'OpenVPN', 'IPsec', 'PKI'],
        'missions' => ['Audit de sécurité', 'Test d\'intrusion (périmétrique)', 'Plan de sécurisation', 'Accompagnement conformité NIS2'],
    ],
    [
        'id'    => 'serveurs',
        'icon'  => 'server',
        'title' => 'Infrastructure & serveurs',
        'short' => 'Proxmox, VMware, Linux, Docker, haute disponibilité',
        'desc'  => 'Conception et opération d\'infrastructures virtualisées haute disponibilité. Expertise sur Proxmox VE, VMware vSphere, conteneurisation Docker, orchestration et stockage distribué (Ceph, ZFS).',
        'tech'  => ['Proxmox VE', 'VMware', 'Docker', 'Linux', 'Ceph', 'ZFS', 'Windows Server', 'Ansible'],
        'missions' => ['Architecture infrastructure', 'Migration virtualisation', 'Infogérance', 'Haute disponibilité'],
    ],
    [
        'id'    => 'reseau',
        'icon'  => 'network',
        'title' => 'Réseau & télécoms',
        'short' => 'BGP AS61193, MikroTik, VXLAN/EVPN, SD-WAN',
        'desc'  => 'Architecte réseau avec un ASN BGP public opéré (AS61193). Expertise en routing avancé, VXLAN/EVPN, SD-WAN, et sécurité réseau. Technologies MikroTik, Cisco, Fortinet, Ubiquiti.',
        'tech'  => ['MikroTik', 'Cisco', 'Fortinet', 'Ubiquiti', 'BGP', 'VXLAN', 'EVPN', 'OSPF', 'MPLS'],
        'missions' => ['Audit réseau', 'Architecture WAN/LAN', 'SD-WAN', 'Opérateur BGP'],
    ],
    [
        'id'    => 'erp',
        'icon'  => 'briefcase',
        'title' => 'ERP & transformation digitale',
        'short' => 'Dolibarr, n8n, automatisation, intégrations API',
        'desc'  => 'Déploiement et personnalisation d\'ERP (Dolibarr), conception de workflows d\'automatisation avec n8n, intégration CRM/ERP, enrichissement IA des données. Expérience DSI en contexte PME et scale-up.',
        'tech'  => ['Dolibarr', 'n8n', 'WooCommerce', 'REST API', 'Python', 'Make.com'],
        'missions' => ['Déploiement ERP', 'Automatisation processus', 'Intégration CRM', 'Formation équipes'],
    ],
    [
        'id'    => 'strategie',
        'icon'  => 'cpu',
        'title' => 'Stratégie IA & innovation',
        'short' => 'IA vidéo, LLM, vision par ordinateur, produit',
        'desc'  => 'Stratégie et déploiement de solutions IA en production. Expertise en IA vidéo (JAGUAR/LYNX via Odonaview), intégration LLM pour l\'automatisation métier, et management produit IA de A à Z.',
        'tech'  => ['Vision par ordinateur', 'LLM', 'Python', 'FastAPI', 'ONVIF', 'Edge AI'],
        'missions' => ['Audit IA', 'POC IA vidéo', 'Intégration LLM', 'Stratégie data'],
    ],
];

// ─── STATS ──────────────────────────────────────────────────────────────────
$stats = [
    ['value' => '10+',    'label' => 'ans d\'expérience',           'icon' => 'calendar'],
    ['value' => 'AS61193','label' => 'ASN BGP public opéré',        'icon' => 'globe'],
    ['value' => '5',      'label' => 'sites critiques sécurisés',   'icon' => 'shield'],
    ['value' => '2',      'label' => 'entreprises dirigées',        'icon' => 'briefcase'],
];

// ─── CLIENTS / PARTENAIRES ───────────────────────────────────────────────────
$clients = [
    ['name' => 'EDF',           'logo' => '/assets/img/clients/edf.svg'],
    ['name' => 'Thales',        'logo' => '/assets/img/clients/thales.svg'],
    ['name' => 'ORANO',         'logo' => '/assets/img/clients/orano.svg'],
    ['name' => 'Eutelsat',      'logo' => '/assets/img/clients/eutelsat.svg'],
    ['name' => 'RTE',           'logo' => '/assets/img/clients/rte.svg'],
    ['name' => 'TotalEnergies', 'logo' => '/assets/img/clients/totalenergies.svg'],
    ['name' => 'GreenYellow',   'logo' => '/assets/img/clients/greenyellow.png'],
];

// ─── STACK SYIT ─────────────────────────────────────────────────────────────
$syit_stack = [
    ['name' => 'MikroTik',     'logo' => '/assets/img/logos/mikrotik.png',  'cat' => 'Réseau'],
    ['name' => 'Cisco',        'logo' => '/assets/img/logos/cisco.svg',     'cat' => 'Réseau'],
    ['name' => 'Fortinet',     'logo' => '/assets/img/logos/fortinet.svg',  'cat' => 'Sécurité'],
    ['name' => 'Ubiquiti',     'logo' => '/assets/img/logos/ubiquiti.svg',  'cat' => 'Réseau'],
    ['name' => 'pfSense',      'logo' => '',                                'cat' => 'Sécurité'],
    ['name' => 'Proxmox',      'logo' => '/assets/img/logos/proxmox.svg',   'cat' => 'Virtualisation'],
    ['name' => 'VMware',       'logo' => '/assets/img/logos/vmware.svg',    'cat' => 'Virtualisation'],
    ['name' => 'Docker',       'logo' => '/assets/img/logos/docker.svg',    'cat' => 'Conteneurs'],
    ['name' => 'Linux',        'logo' => '/assets/img/logos/linux.svg',     'cat' => 'OS'],
    ['name' => 'Windows Server','logo' => '',                               'cat' => 'OS'],
];
